### PR TITLE
Create 2022-05-17

### PR DESCRIPTION
**Pull request by shannona**

### CODE REVIEW

**Comment by shannona** [comment]
This is a draft of an announcement of the Silicon Salon.

Prior to its release we need to release the Eventbrite announcement and then link that in here.

**Comment by ChristopherA** [comment]
Change Proxy's presentation info to "building flexibility and future-proofing into hardware products"

**Comment by ChristopherA** [comment]
We need to say a little more about Tropic Square's plans and what they might present.

**Comment by shannona** [comment]
Changes made.

**Pull request merged**
